### ISSUE TITLE
polybar中的common.py 里面有个文件的引用无法找到

### ISSUE THREAD

**Issue by zhaoNjust** [gxt-kt/dotfiles#2]
FILE_PATH = "~/.cache/polybar_title.yaml"

**Comment by gogongxt** [comment]
这里是指名配置文件的路径
在代码使用中如果文件不存在会进行创建，所以没关系。
可以看代码：
https://github.com/gxt-kt/dotfiles/blob/ccedba0e713adade22e1493e793004f6dceb09da/polybar/.config/polybar/nord/modules/common.py#L8-L9

当然如果你的.cache目录不存在，可能会有问题，一般linux底下都是存在的
